---
- name: Create docker-compose project directory, in cache path
  file: state=directory path="{{ dct_cache_path }}" mode="0700"

- name: Transfer docker-compose project to remote cache path
  synchronize:
    src: "{{ project | mandatory }}"
    dest: "{{ dct_cache_path }}"
    recursive: True
    delete: True
    rsync_opts:
      - "--usermap='*:{{ hostvars[inventory_hostname].ansible_user_uid }}'"
      - "--groupmap='*:{{ hostvars[inventory_hostname].ansible_user_gid }}'"

- name: "Build and deploy project {% if dct_reminder == True %}({{ dct_reminder_message }}){% endif %}"
  docker_service: project_src='{{ dct_cache_path }}/{{ project | basename }}' recreate='{% if dct_recreate == True %}always{% else %}smart{% endif %}'
